### ISSUE TITLE
License situation is very unclear

### ISSUE THREAD

**Issue by sullivanmj** [adafruit/AdafruitClassLibrary#14]
The license situation for this repository is very unclear, given the following:

- There is no LICENSE file in the repository
- Yet several source code files (e.g. GPS.cs) have a header that contains the text string below, which is **not** the MIT license.
> Adafruit Class Library is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> MIT license, all text above must be included in any redistribution.
- The [Nuget Gallery page for AdafruitClassLibrary](https://www.nuget.org/packages/AdafruitClassLibrary/) also specifies that the nuget package (but not necessarily the source code) is distributed under the MIT license, but links to a generic MIT license template that does not specify a copyright holder or year.

**Comment by ladyada** [comment]
thanks this library is deeply unsupported at this time. if you submit a PR with MIT license designations and files, we'd merge it.

**Comment by sullivanmj** [comment]
Great, I'd be happy to do so. I'll make the copyright holder "Adafruit Industries, LLC" unless you specify otherwise.

**Comment by ladyada** [comment]
that would be wonderful :)
